branch-defaults:
  develop:
    environment: WebTickets-Backend-dev
deploy:
  artifact: build/libs/gs-spring-boot-0.1.0.jar
environment-defaults:
  named-parking-spot-dev:
    branch: circleci
    repository: null
global:
  application_name: qpark-mobile-parking-production-server
  default_ec2_keyname: StagingKey
  default_platform: arn:aws:elasticbeanstalk:eu-west-1::platform/Java 8 running on
    64bit Amazon Linux/2.9.2
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
